[ec2]
# Ganti YOUR_EC2_PUBLIC_IP dengan IP Publik EC2 Anda
# Ganti /path/to/your-key.pem dengan path SSH Key (.pem) Anda
ec2_instance ansible_host=YOUR_EC2_PUBLIC_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/your-key.pem
